# Generated by Django 5.2.5 on 2025-09-06 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MiniFig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fig_num', models.CharField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('num_parts', models.IntegerField()),
            ],
            options={
                'ordering': ['fig_num'],
                'indexes': [models.Index(fields=['fig_num'], name='brickbuddy__fig_num_aff234_idx')],
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='brickbuddy__name_804eb5_idx')],
            },
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_num', models.CharField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('year', models.IntegerField()),
                ('num_parts', models.IntegerField()),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sets', to='brickbuddy.theme')),
            ],
            options={
                'ordering': ['-year', 'name'],
                'indexes': [models.Index(fields=['year'], name='brickbuddy__year_9863cc_idx'), models.Index(fields=['name'], name='brickbuddy__name_768507_idx'), models.Index(fields=['theme', 'year'], name='brickbuddy__theme_i_47aa34_idx')],
            },
        ),
    ]
